Html:
    Replace:
        '--': '&ndash;'
Tex:
    Replace:
        '%': '\%'
        '#': '\#'
Partials:
    CommaSep: "{{Item}}{{^IsLast}}, {{/IsLast}}"
Macros:
    Subsection: |
        <div class="subsection">
            <h3>{}</h3>
            <p class="subtitle">{}</p>
            {}
        </div>
    Subsubsection: |
        <div class="subsubsection">
            <h4>{}</h4>
            <p class="subtitle">{}</p>
            {}
        </div>